# Generated by Django 4.2.2 on 2023-06-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('R', 'ROMANCE'), ('D', 'DRAMA'), ('C', 'COMEDY'), ('A', 'ACTION')], max_length=1),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='movie_image'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('GR', 'GERMAN'), ('EN', 'ENGLISH')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('MW', 'MOST WATCHED'), ('TR', 'TOP RATED'), ('RA', 'RESENTLY ADDED')], max_length=2),
        ),
    ]
