# Generated by Django 4.2.2 on 2023-06-12 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_category_alter_movie_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('C', 'COMEDY'), ('R', 'ROMANCE'), ('D', 'DRAMA'), ('A', 'ACTION')], max_length=1),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('EN', 'ENGLISH'), ('GR', 'GERMAN')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('TR', 'TOP RATED'), ('MW', 'MOST WATCHED'), ('RA', 'RESENTLY ADDED')], max_length=2),
        ),
        migrations.CreateModel(
            name='Movie_Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('D', 'DOWNLOAD_LINKS'), ('W', 'WATCH_LINKS')], max_length=1)),
                ('links', models.URLField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_links', to='movie.movie')),
            ],
        ),
    ]
