# Generated by Django 4.2.2 on 2023-06-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_cast_alter_movie_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('action', 'ACTION'), ('comedy', 'COMEDY'), ('drama', 'DRAMA'), ('romance', 'ROMANCE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('GR', 'GERMAN'), ('EN', 'ENGLISH')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('MW', 'MOST WATCHED'), ('RA', 'RESENTLY ADDED'), ('TR', 'TOP RATED')], max_length=2),
        ),
    ]
