# Generated by Django 4.2.2 on 2023-06-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_category_alter_movie_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('comedy', 'COMEDY'), ('romance', 'ROMANCE'), ('drama', 'DRAMA'), ('action', 'ACTION')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('EN', 'ENGLISH'), ('GR', 'GERMAN')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('TR', 'TOP RATED'), ('RA', 'RESENTLY ADDED'), ('MW', 'MOST WATCHED')], max_length=2),
        ),
    ]
