# Generated by Django 4.2.2 on 2023-06-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_movie_slug_alter_movie_category_alter_movie_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('drama', 'DRAMA'), ('romance', 'ROMANCE'), ('comedy', 'COMEDY'), ('action', 'ACTION')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('TR', 'TOP RATED'), ('RA', 'RESENTLY ADDED'), ('MW', 'MOST WATCHED')], max_length=2),
        ),
    ]
