# Generated by Django 4.2.2 on 2023-06-13 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_movie_trailer_alter_movie_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 13, 14, 40, 28, 488421, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('action', 'ACTION'), ('romance', 'ROMANCE'), ('drama', 'DRAMA'), ('comedy', 'COMEDY')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('MW', 'MOST WATCHED'), ('RA', 'RESENTLY ADDED'), ('TR', 'TOP RATED')], max_length=2),
        ),
    ]
