# Generated by Django 4.2.2 on 2023-06-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_movie_banner_alter_movie_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('romance', 'ROMANCE'), ('action', 'ACTION'), ('drama', 'DRAMA'), ('comedy', 'COMEDY')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('german', 'GERMAN'), ('english', 'ENGLISH')], max_length=10),
        ),
    ]
